=== marcibaumel/O09CTQ_XMLGyak/O09CTQ_1012/BM_nevjegykartya.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:complexType name="egyetem">
    <xs:sequence>
        <xs:element name="iranyitoszam" type="xs:string"/>
        <xs:element name="varos" type="xs:string"/>
        <xs:element name="utca" type="xs:string"/>
        <xs:element name="hazszam" type="xs:string"/>
        <xs:element name="telefonszam" type="xs:string"/>
        <xs:element name="weblap" type="xs:string"/>
    </xs:sequence>
</xs:complexType>
    <xs:element name="nevjegykartya">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="nev" type="xs:string"/>
                <xs:element name="egyetem" type="egyetem"/>
                <xs:element name="beosztas" type="xs:string"/>
                <xs:element name="telefonszam" type="xs:string"/>
                <xs:element name="email" type="xs:string"/>
                <xs:element name="abstract" type="xs:string"/> 
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== marcibaumel/O09CTQ_XMLGyak/O09CTQ_1012/BM_nevjegykartya.xml
<?xml version="1.0" encoding="UTF-8"?>

<nevjegykartya xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BM_nevjegykartya.xsd">
    <nev>Baumel Márton</nev>
    <egyetem>
        <iranyitoszam>3500</iranyitoszam>
        <varos>Miskolc</varos>
        <utca>Miskolc utca</utca>
        <hazszam>12</hazszam>
        <telefonszam>+3131313</telefonszam>
        <weblap>www.miskolc.hu</weblap>
    </egyetem>
    <beosztas>Tanuló</beosztas>
    <telefonszam>21213131</telefonszam>
    <email>marcibaumel@gmail.com</email>
    <abstract></abstract>
</nevjegykartya>
