=== marcibaumel/O09CTQ_XMLGyak/XMLTaskO09CTQ/DOMParseO09CTQ/XMLSchemaO09CTQ.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
    <xs:element name="Office">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="Employees">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Employee" type="employeeType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Departments">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Department" type="departmentType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Warehouses">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Warehouse" type="warehouseType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Permissions">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Permission" type="permissionType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>


                <xs:element name="Licenses">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="License" type="licenseType" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>

        <xs:key name="EmployeeId_FK">
			<xs:selector xpath="Employees/Employee"/>
			<xs:field xpath="@EmployeeId"/>
		</xs:key>

        <xs:key name="DepartmentId_FK">
			<xs:selector xpath="Departments/Department"/>
			<xs:field xpath="@DepartmentId"/>
		</xs:key>

        <xs:key name="PermissionId_FK">
			<xs:selector xpath="Permissions/Permission"/>
			<xs:field xpath="@PermissionId"/>
		</xs:key>

        <xs:keyref name="EmployeeId_FK-License" refer="EmployeeId_FK">
			<xs:selector xpath="Licenses/License/EmployeeId_FK"/>
            <xs:field xpath="."/>
        </xs:keyref>

        <xs:keyref name="PermissionId_FK-License" refer="PermissionId_FK">
			<xs:selector xpath="Licenses/License/PermissionId_FK"/>
            <xs:field xpath="."/>
        </xs:keyref>

        <xs:keyref name="DepartmentId_FK-Employee" refer="DepartmentId_FK">
			<xs:selector xpath="Employees/Employee/DepartmentId_FK"/>
            <xs:field xpath="."/>
        </xs:keyref>

    </xs:element>

    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element name="Country" type="xs:string"/>
            <xs:element name="Postcode" type="xs:string"/>
            <xs:element name="City" type="xs:string"/>
            <xs:element name="Street" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="employeeType">
        <xs:sequence>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Phone" type="xs:string"/>
            <xs:element name="Email" type="xs:string"/>
            <xs:element name="DepartmentId_FK" type="xs:integer"/>
            
        </xs:sequence>
        <xs:attribute name="EmployeeId" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-9][0-9][0-9]"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>


    <xs:complexType name="departmentType">
        <xs:sequence>
            <xs:element name="Address" type="addressType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Email" type="xs:string"/>
            <xs:element name="Website" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="DepartmentId" use="required">
            <xs:simpleType>
                <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-9][0-9]"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="warehouseType">
        <xs:sequence>
            <xs:element name="Item" type="itemType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="Address" type="addressType" minOccurs="1" maxOccurs="1"/>
            <xs:element name="Email" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="WarehouseId" type="xs:integer" use="required"/>
    </xs:complexType>


    <xs:complexType name="itemType">
        <xs:sequence>
            <xs:element name="ItemName" type="xs:string"  maxOccurs="1"/>
            <xs:element name="ItemQuantity" type="xs:integer" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="permissionType">
        <xs:sequence>
            <xs:element name="Role" type="xs:string"/>
            <xs:element name="Modified" type="xs:date"/>
            <xs:element name="Computer" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="PermissionId" type="xs:integer" use="required"/>
    </xs:complexType>

    <xs:complexType name="licenseType">
        <xs:sequence>
            <xs:element name="EmployeeId_FK" type="xs:integer"/>
            <xs:element name="PermissionId_FK" type="xs:integer"/>
            <xs:element name="Active" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== marcibaumel/O09CTQ_XMLGyak/XMLTaskO09CTQ/DOMParseO09CTQ/XMLO09CTQ2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Office xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaO09CTQ.xsd">
        
    
    <Employees>
                
        <Employee EmployeeId="100">
                        
            <Name>Kis Béla</Name>
                        
            <Phone>06308881983</Phone>
                        
            <Email>belaÚJ@email.com</Email>
                        
            <DepartmentId_FK>01</DepartmentId_FK>
                    
        </Employee>
                
        <Employee EmployeeId="101">
                        
            <Name>Nagy Ernő</Name>
                        
            <Phone>06308881984</Phone>
                        
            <Email>erno@email.com</Email>
                        
            <DepartmentId_FK>01</DepartmentId_FK>
                    
        </Employee>
                
        <Employee EmployeeId="102">
                        
            <Name>Baumel Márton</Name>
                        
            <Phone>06308881985</Phone>
                        
            <Email>marton@email.com</Email>
                        
            <DepartmentId_FK>02</DepartmentId_FK>
                    
        </Employee>
            
    </Employees>
        
    <Departments>
                
        <Department DepartmentId="01">
                        
            <Address>
                                
                <Country>Hungary</Country>
                                
                <Postcode>3900</Postcode>
                                
                <City>Szerencs</City>
                                
                <Street>Hársfa utca 14</Street>
                            
            </Address>
                        
            <Email>marcibaumel@gmai.com</Email>
                        
            <Website>szerencswebsite.hu</Website>
                    
        </Department>
                
        <Department DepartmentId="02">
                        
            <Address>
                                
                <Country>Hungary</Country>
                                
                <Postcode>1055</Postcode>
                                
                <City>Budapest</City>
                                
                <Street>Kossuth Lajos tér 1-3</Street>
                            
            </Address>
                        
            <Email>miskolc@nememail.com</Email>
                        
            <Website>miskolciceg.hu</Website>
                    
        </Department>
            
    </Departments>
        
    <Warehouses>
                
        <Warehouse WarehouseId="01">
                        
            <Item>
                                
                <ItemName>Paper</ItemName>
                                
                <ItemQuanitity>100</ItemQuanitity>
                            
            </Item>
                        
            <Item>
                                
                <ItemName>scissors</ItemName>
                                
                <ItemQuanitity>200</ItemQuanitity>
                            
            </Item>
                        
            <Address>
                                
                <Country>Hungary</Country>
                                
                <Postcode>3515</Postcode>
                                
                <City>Miskolc</City>
                                
                <Street>Egyetemi út 2</Street>
                            
            </Address>
                        
            <Email>warehousemiskolc@email.com</Email>
                    
        </Warehouse>
                
        <Warehouse WarehouseId="02">
                        
            <Item>
                                
                <ItemName>Paper</ItemName>
                                
                <ItemQuanitity>100</ItemQuanitity>
                            
            </Item>
                        
            <Address>
                                    
                <Country>Hungary</Country>
                                    
                <Postcode>3900</Postcode>
                                    
                <City>Szerencs</City>
                                    
                <Street>Hársfa utca 14</Street>
                            
            </Address>
                        
            <Email>warehouseszerencs@email.com</Email>
                    
        </Warehouse>
            
    </Warehouses>
        
    <Permissions>
                
        <Permission PermissionId="1">
                        
            <Role>admin</Role>
                        
            <Modified>2021-11-23</Modified>
                        
            <Computer>01</Computer>
                    
        </Permission>
                
        <Permission PermissionId="2">
                        
            <Role>user</Role>
                        
            <Modified>2021-06-12</Modified>
                        
            <Computer>03</Computer>
                    
        </Permission>
            
    </Permissions>
        
    <Licenses>
                
        <License>
                        
            <EmployeeId_FK>100</EmployeeId_FK>
                        
            <PermissionId_FK>1</PermissionId_FK>
                        
            <Active>true</Active>
                    
        </License>
                
        <License>
                        
            <EmployeeId_FK>101</EmployeeId_FK>
                        
            <PermissionId_FK>2</PermissionId_FK>
                        
            <Active>false</Active>
                    
        </License>
                
        <License>
                        
            <EmployeeId_FK>102</EmployeeId_FK>
                        
            <PermissionId_FK>1</PermissionId_FK>
                        
            <Active>false</Active>
                    
        </License>
            
    </Licenses>
    
</Office>

=== marcibaumel/O09CTQ_XMLGyak/XMLTaskO09CTQ/DOMParseO09CTQ/XMLO09CTQ.xml
<?xml version="1.0" encoding="UTF-8"?>

<Office xsi:noNamespaceSchemaLocation="XMLSchemaO09CTQ.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    
    <Employees>
        <Employee EmployeeId="100">
            <Name>Kis Béla</Name>
            <Phone>06308881983</Phone>
            <Email>bela@email.com</Email>
            <DepartmentId_FK>01</DepartmentId_FK>
        </Employee>
        <Employee EmployeeId="101">
            <Name>Nagy Ernő</Name>
            <Phone>06308881984</Phone>
            <Email>erno@email.com</Email>
            <DepartmentId_FK>01</DepartmentId_FK>
        </Employee>
        <Employee EmployeeId="102">
            <Name>Baumel Márton</Name>
            <Phone>06308881985</Phone>
            <Email>marton@email.com</Email>
            <DepartmentId_FK>02</DepartmentId_FK>
        </Employee>
    </Employees>

    <Departments>
        <Department DepartmentId="01">
            <Address>
                <Country>Hungary</Country>
                <Postcode>3900</Postcode>
                <City>Szerencs</City>
                <Street>Hársfa utca 14</Street>
            </Address>
            <Email>marcibaumel@gmai.com</Email>
            <Website>szerencswebsite.hu</Website>
        </Department>

        <Department DepartmentId="02">
            <Address>
                <Country>Hungary</Country>
                <Postcode>3515</Postcode>
                <City>Miskolc</City>
                <Street>Egyetemi út 1</Street>
            </Address>
            <Email>miskolc@nememail.com</Email>
            <Website>miskolciceg.hu</Website>
        </Department>
    </Departments>

    <Warehouses>
        <Warehouse WarehouseId="01">
            <Item>
                <ItemName>Paper</ItemName>
                <ItemQuantity>100</ItemQuantity>
            </Item>
            <Item>
                <ItemName>scissors</ItemName>
                <ItemQuantity>200</ItemQuantity>
            </Item>
            <Address>
                <Country>Hungary</Country>
                <Postcode>3515</Postcode>
                <City>Miskolc</City>
                <Street>Egyetemi út 2</Street>
            </Address>
            <Email>warehousemiskolc@email.com</Email>
        </Warehouse>

        <Warehouse WarehouseId="02">
            <Item>
                <ItemName>Paper</ItemName>
                <ItemQuantity>100</ItemQuantity>
            </Item>
            <Address>
                    <Country>Hungary</Country>
                    <Postcode>3900</Postcode>
                    <City>Szerencs</City>
                    <Street>Hársfa utca 14</Street>
            </Address>
            <Email>warehouseszerencs@email.com</Email>
        </Warehouse>
    </Warehouses>

    <Permissions>
        <Permission PermissionId="1">
            <Role>admin</Role>
            <Modified>2021-06-12</Modified>
            <Computer>01</Computer>
        </Permission>

        <Permission PermissionId="2">
            <Role>user</Role>
            <Modified>2021-06-12</Modified>
            <Computer>03</Computer>
        </Permission>
    </Permissions>

    <Licenses>
        <License>
            <EmployeeId_FK>100</EmployeeId_FK>
            <PermissionId_FK>1</PermissionId_FK>
            <Active>true</Active>
        </License>
        <License>
            <EmployeeId_FK>101</EmployeeId_FK>
            <PermissionId_FK>2</PermissionId_FK>
            <Active>false</Active>
        </License>
        <License>
            <EmployeeId_FK>102</EmployeeId_FK>
            <PermissionId_FK>1</PermissionId_FK>
            <Active>false</Active>
        </License>
    </Licenses>
</Office>
