=== marcibaumel/O09CTQ_XMLGyak/O09CTQ_1019/szemelyekO09CTQ.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="szemelyek">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="szemely" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nev" type="xs:string"/>
                            <xs:element name="kor" type="xs:string"/>
                            <xs:element name="varos" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>
</xs:schema>

=== marcibaumel/O09CTQ_XMLGyak/O09CTQ_1019/szemelyekO09TQ.xml
<?xml version="1.0" encoding="UTF-8"?>
<szemelyek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="szemelyekO09CTQ.xsd">

    <szemely id="01">
        <nev>Baumel Márton</nev>
        <kor>20</kor>
        <varos>Szerencs</varos>
    </szemely>

    <szemely id="02">
        <nev>Bab Erik</nev>
        <kor>70</kor>
        <varos>Miskolc</varos>
    </szemely>

    <szemely id="03">
        <nev>Ek Gergő</nev>
        <kor>10</kor>
        <varos>Budapest</varos>
    </szemely>
</szemelyek>
