=== marcibaumel/O09CTQ_XMLGyak/O09CTQ_1005/BM_konyv.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="konyvek">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="konyv" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cime" type="xs:string"/>
                            <xs:element name="ev" type="xs:unsignedShort"/>
                            <xs:element name="kiado" type="xs:string"/>
                            <xs:element name="szerzo" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="abstract" type="xs:string"/> 
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>
</xs:schema>

=== marcibaumel/O09CTQ_XMLGyak/O09CTQ_1005/BM_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>

<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="BM_konyv.xsd">

        <konyv id="01">
            <cime>Clean Code</cime>
            <ev>2008</ev>
            <kiado>Pearson Education (US)</kiado>
            <szerzo>Robert C. Martin</szerzo>
            <abstract></abstract>
        </konyv>

        <konyv id="02">
            <cime>Clean Architecture : A Craftsman's Guide to Software Structure and Design</cime>
            <ev>2017</ev>
            <kiado>Pearson Education (US)</kiado>
            <szerzo>Robert C. Martin</szerzo>
            <abstract></abstract>
        </konyv>

        <konyv id="03">
            <cime>Refactoring : Improving the Design of Existing Code</cime>
            <ev>2019</ev>
            <kiado>Pearson Education (US)</kiado>
            <szerzo>Martin Fowler</szerzo>
            <abstract></abstract>
        </konyv>

    </konyvek>
